### Register user
POST http://localhost:5000/register
Content-Type: application/json

//{
//  "name": "Samwell Tarly",
//  "email": "jerk2@nightwatch.nrd",
//  "username": "Snowball",
//  "password": "aaa"
//}

{
  "name": "John Snow",
  "email": "jerk@nightwatch.nrd",
  "username": "Snowball",
  "password": "aaa"
}

### Authenticate user
POST http://localhost:5000/authenticate
Content-Type: application/json

{
  "email": "jerk@nightwatch.nrd",
  "password": "aaaa"
}

### Refresh access token
POST http://localhost:5000/refresh_token


### Defalut invalid endpoint
GET http://localhost:5000/

### Secure endpoint
GET http://localhost:5000/users